name: project_sanbercode
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore: 4.0.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_storage: 11.0.5
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
